### ISSUE TITLE
Remove test files on EditYaml run

### ISSUE THREAD

**Issue by curlyjason** [curlyjason/cake5docker#14]
This is a (multiple allowed):

* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

### What you did
Standard migration, following Read Me instructions

### What happened
Exactly what we expected

### What you expected to happen
We want to also delete all the files associated with the test 'First' table that in the setup.

Remove with shell script, as a part of EditYaml

<img width="542" alt="Screenshot 2023-11-03 at 2 47 57 PM" src="https://github.com/curlyjason/cake5docker/assets/1307159/3f6a5fc6-6b9d-490f-af49-f0a0f879fc97">

**Comment by dreamingmind** [comment]
we'll have to restore these files before we can write the removal too :-)
